# Generated by Django 4.1.1 on 2022-10-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="detial",
            new_name="detail",
        ),
    ]
